version: 2
jobs:
  build:
    docker:
        - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
        - checkout
        - run: ls -alt
        - run: npm install
        - run: npm install -g aws-sdk
        - run: npm run build
        - run: cdk synth
        - run: cdk deploy --require-approval=never