version: 2
jobs:
  build:
    docker:
        - image: circleci/node:lts
        - volumes:
    working_directory: ~/repo
    steps:
        - checkout
        - setup_remote_docker
        - run: npm -v
        - run: node -v
        - run: npm install -d
        - run: ls node_modules
        - run: npm run build
        - run: npm run cdk synth
        - run: echo "y" |  node ./node_modules/aws-cdk/bin/cdk.js deploy  --require-approval=never