version: 2
jobs:
  build:
    # machine: true
    docker:
        - image: circleci/node:lts
    working_directory: ~/repo
    steps:
        - checkout
        - run: cat /etc/os-release
        # - run:
        #     name: "Update Node.js and npm"
        #     command: |
        #       curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
        #       curl https://www.npmjs.com/install.sh | sudo bash
        # - run: sudo apt-get update -y
        # - run: sudo apt-get upgrade --fix-missing
        # - run: sudo apt-get install curl
        # - run: sudo curl -fsSL https://get.docker.com / | sh
        # - run: sudo usermod -aG docker $USER
        # - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
        # - run: sudo apt-get install -y nodejs
        - run: npm -v
        - run: node -v
        # - run: sudo docker ps
        # - run: docker ps
        # - run: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
        # - run: PATH=$PATH:/opt/circleci/.nvm
        # - run: export PATH
        # - run: source ~/.bashrc
        # - run: nvm install 10.16.3
        # - run: nvm use 10.16.3
        # - run: node -v
        # - run: npm install -d
        # - run: ls node_modules
        # - run: npm run build
        # - run: node ./node_modules/aws-cdk/bin/cdk.js synth
        - setup_remote_docker:
            version: 18.06.0-ce
        - run: pwd
        - run: ls -alt /var/run/
        # - run: sudo dockerd
        # - run: ssh-docker ls -alt
        # - run: docker container ls -a
        # - run: echo "y" |  node ./node_modules/aws-cdk/bin/cdk.js deploy  --require-approval=never